import { main, searchBtn } from "@/style/color";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header
          className="w-full h-24 flex justify-between  items-cente"
          style={{ backgroundColor: main }}
        >
          <a
            style={{ borderRight: "1px solid #333" }}
            className="border-r text-center flex justify-around box-border p-3 items-center flex-1 "
            href="/"
          >
            <Image
              alt="シェア"
              src="/image/camera.svg"
              width={35}
              height={35}
              className="m-2"
            />
            <p>share</p>
          </a>
          <a
            style={{ borderRight: "1px solid #333" }}
            className="border-r text-center flex justify-around box-border p-3 items-center flex-1"
            href="/about"
          >
            <Image
              alt="遠回り"
              src="/image/root.svg"
              width={35}
              height={35}
              className="m-2"
            />
            <p>detour</p>
          </a>
          <a
            className=" text-center flex justify-around box-border p-3 items-center flex-1"
            href="/about"
          >
            <Image
              alt="方向"
              src="/image/direction.svg"
              width={35}
              height={35}
              className="m-2"
            />
          </a>
        </header>
        <main className="h-4/5">
          {children}
          <div
            className="w-full flex justify-center items-end text-xs h-16 absolute bottom-16 "
            style={{ backgroundColor: main }}
          >
            <a
              className="flex  items-center flex-col justify-center text-center  flex-1 "
              href="/#"
            >
              <Image
                alt="現在地"
                src="/image/now.svg"
                width={30}
                height={30}
                className="m-1"
              />
              <p> 現在地</p>
            </a>
            <a
              className="w-24 h-24  rounded-full  flex  items-center flex-col justify-center text-center   before:content-[''] "
              style={{ backgroundColor: searchBtn }}
              href="/#"
            >
              <Image
                alt="検索"
                src="/image/search.svg"
                width={42}
                height={42}
                className="m-1"
              />
            </a>
            <a
              className="flex  items-center flex-col justify-center text-center  flex-1 "
              href="/#"
            >
              <Image
                alt="スケジュール"
                src="/image/schedule.svg"
                width={30}
                height={30}
                className="m-1"
              />
              <p> スケジュール</p>
            </a>
          </div>
        </main>
        {/* 広告 */}
        <div className="w-full h-16 bg-slate-200 text-center absolute bottom-0">
          PR
        </div>
      </body>
    </html>
  );
}
